### ISSUE TITLE
Clang 20 incompatibility

### ISSUE THREAD

**Issue by mkannwischer** [Neo-Outis/CT-LLVM-Artifact#3]
I tried integration of CT-LLVM into mlkem-native: https://github.com/pq-code-package/mlkem-native/pull/1101

I found that it does not compile with clang 20 (20.1.4):
```
ctllvm.cpp:1472:9: error: no viable conversion from '(lambda at ctllvm.cpp:1472:9)' to 'const std::function<void (ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase)>' (a>
 1472 |         [&](ModulePassManager &MPM, OptimizationLevel Level) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1473 |           MPM.addPass(CTPass());
      |           ~~~~~~~~~~~~~~~~~~~~~~
 1474 |           return true;
      |           ~~~~~~~~~~~~
 1475 |         });
      |         ~
/nix/store/sqrva45cn81kg9nm48l2jpizklwxmfxd-libcxx-20.1.4-dev/include/c++/v1/__functional/function.h:862:25: note: candidate constructor not viable: no known conversion from '(la>
  862 |   _LIBCPP_HIDE_FROM_ABI function(nullptr_t) _NOEXCEPT {}
      |                         ^        ~~~~~~~~~
/nix/store/sqrva45cn81kg9nm48l2jpizklwxmfxd-libcxx-20.1.4-dev/include/c++/v1/__functional/function.h:863:25: note: candidate constructor not viable: no known conversion from '(la>
  863 |   _LIBCPP_HIDE_FROM_ABI function(const function&);
      |                         ^        ~~~~~~~~~~~~~~~
/nix/store/sqrva45cn81kg9nm48l2jpizklwxmfxd-libcxx-20.1.4-dev/include/c++/v1/__functional/function.h:864:25: note: candidate constructor not viable: no known conversion from '(la>
  864 |   _LIBCPP_HIDE_FROM_ABI function(function&&) _NOEXCEPT;
      |                         ^        ~~~~~~~~~~
/nix/store/sqrva45cn81kg9nm48l2jpizklwxmfxd-libcxx-20.1.4-dev/include/c++/v1/__functional/function.h:866:25: note: candidate template ignored: requirement '__callable<(lambda at >
  866 |   _LIBCPP_HIDE_FROM_ABI function(_Fp);
      |                         ^
/nix/store/n61fni7823sxxiiwcg754h0wjrlpvkz2-llvm-20.1.4-dev/include/llvm/Passes/PassBuilder.h:504:54: note: passing argument to parameter 'C' here
  504 |                                ThinOrFullLTOPhase)> &C) {
      |                                                      ^
```

There seem to be some API changes unfortunately. Do you think you will be able to support it?

**Comment by Neo-Outis** [comment]
Fixed, tested and pushed. LLVM likes changing API : )

**Comment by mkannwischer** [comment]
Thanks. I tested it and can confirm that it works with clang 20.
