### ISSUE TITLE
Clang 15 incompatibility

### ISSUE THREAD

**Issue by mkannwischer** [Neo-Outis/CT-LLVM-Artifact#4]
I tried integration of CT-LLVM into mlkem-native: https://github.com/pq-code-package/mlkem-native/pull/1101

I found that it does not compile with clang 15 (15.0.7):

```
ctllvm.cpp:340:24: error: no member named 'ends_with' in 'llvm::StringRef'; did you mean 'endswith'?
  StringRef funcName = FUNC_NAME_ENDS_WITH(F.getName(), "_ctcloned")
                       ^
ctllvm.cpp:68:49: note: expanded from macro 'FUNC_NAME_ENDS_WITH'
#define FUNC_NAME_ENDS_WITH(name, suffix) (name.ends_with(suffix))
                                                ^
/nix/store/1zxqw3vqasvbz083w8r535pnh6a173qq-llvm-15.0.7-dev/include/llvm/ADT/StringRef.h:301:10: note: 'endswith' declared here
    bool endswith(StringRef Suffix) const {
         ^
ctllvm.cpp:768:7: error: no member named 'ends_with' in 'llvm::StringRef'; did you mean 'endswith'?
  if (FUNC_NAME_ENDS_WITH(FunctionName, "_ctcloned"))
      ^
ctllvm.cpp:68:49: note: expanded from macro 'FUNC_NAME_ENDS_WITH'
#define FUNC_NAME_ENDS_WITH(name, suffix) (name.ends_with(suffix))
                                                ^
/nix/store/1zxqw3vqasvbz083w8r535pnh6a173qq-llvm-15.0.7-dev/include/llvm/ADT/StringRef.h:301:10: note: 'endswith' declared here
    bool endswith(StringRef Suffix) const {
```

I find this quite confusing since clang 14 (14.0.6) works fine just like clang 16-19 do. 
Any idea if there is an easy fix for this?

**Comment by Neo-Outis** [comment]
Easy fix : ) Tested and pushed, thanks for the report : )

**Comment by mkannwischer** [comment]
Thanks. I tested it and can confirm that it works with clang 15.
